name: CI (Docker build & test)

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test-in-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ml_test:ci

      - name: Run tests
        run: docker run --rm ml_test:ci pytest -q